[project]
name = "tpdbcollectionmaker"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4==4.12.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
